# TRAVELLING SALESMAN PROBLEM

In [10]:
#import library yang diperlukan

import random
import matplotlib.pyplot as plt
import numpy as np

## MENENTUKAN KOORDINAT KOTA

In [11]:
# Menentukan Koordinat Kota  (coba D E C B A)
#  0 = [0, 0]   -> Kota A
#  1 = [5, 6]   -> Kota B
#  2 = [1, 4]    -> Kota C
#  3 = [3, 4]    -> Kota D
#  4 = [7, 7]  -> Kota E
daftarKota = [[0, 0], [5, 6], [1, 4], [3, 4], [7, 7]]

for i in daftarKota:
    for j in i:
        print(j, end = " ")
    print()

jumlahKota = len(daftarKota)

0 0 
5 6 
1 4 
3 4 
7 7 


## INISIALISASI POPULASI

In [12]:
#Melakukan Inisialisasi Populasi

def initPopulasi(ukuranPopulasi, jumlahKota):
    P = np.empty((ukuranPopulasi, jumlahKota))
    P = P.astype('int')
    seed = np.random.default_rng(123)
    for i in range(ukuranPopulasi):
        I = np.random.permutation(jumlahKota)
        for j in range(jumlahKota):
            P[i][j] = I[j]
    return P

ukuranPopulasi = 4
P = initPopulasi(ukuranPopulasi, jumlahKota)
print(P)

[[0 2 3 1 4]
 [3 0 2 1 4]
 [3 0 4 1 2]
 [1 3 4 2 0]]


In [13]:
#inisialisasi solusi 
I1 = P[0]  # [3 4 2 1 0] --> [D E C B A]
print(I1)
I2 = P[1]
print(I2)
I3 = P[2]
print(I3)
I4 = P[3]
print(I4)

# Menentukan Koordinat Kota  (coba D E C B A)
#  0 = [0, 0]   -> Kota A
#  1 = [5, 6]   -> Kota B
#  2 = [1, 4]    -> Kota C
#  3 = [3, 4]    -> Kota D
#  4 = [7, 7]  -> Kota E


#jarak1 = (((3-7)**2 + (4-7)**2)**(1/2))  +  (((7-1)**2 + (7-4)**2)**(1/2))  +  (((1-5)**2 + (4-6)**2)**(1/2))  +  (((5-0)**2 + (6-0)**2)**(1/2))  +  (((0-3)**2 + (0-4)**2)**(1/2))
#print(jarak1)



[0 2 3 1 4]
[3 0 2 1 4]
[3 0 4 1 2]
[1 3 4 2 0]
28.990589563405603


In [14]:


#hitung jarak pada I1
jarakI1 = 0
for i in range(jumlahKota):
    #print(i)
    jarakI1 += ((daftarKota[I1[i]][0] - daftarKota[I1[(i+1)%jumlahKota]][0])**2 + (daftarKota[I1[i]][1] - daftarKota[I1[(i+1)%jumlahKota]][1])**2)**(1/2)
print("jarak I1 = ", jarakI1)

#hitung jarak pada I2
jarakI2 = 0
for i in range(jumlahKota):
    #print(i)
    jarakI2 += ((daftarKota[I2[i]][0] - daftarKota[I2[(i+1)%jumlahKota]][0])**2 + (daftarKota[I2[i]][1] - daftarKota[I2[(i+1)%jumlahKota]][1])**2)**(1/2)
print("jarak I2 = ", jarakI2)

#hitung jarak pada I3
jarakI3 = 0
for i in range(jumlahKota):
    #print(i)
    jarakI3 += ((daftarKota[I3[i]][0] - daftarKota[I3[(i+1)%jumlahKota]][0])**2 + (daftarKota[I3[i]][1] - daftarKota[I3[(i+1)%jumlahKota]][1])**2)**(1/2)
print("jarak I3 = ", jarakI3)

#hitung jarak pada I4
jarakI4 = 0
for i in range(jumlahKota):
    #print(i)
    jarakI4 += ((daftarKota[I4[i]][0] - daftarKota[I4[(i+1)%jumlahKota]][0])**2 + (daftarKota[I4[i]][1] - daftarKota[I4[(i+1)%jumlahKota]][1])**2)**(1/2)
print("jarak I4 = ", jarakI4)



jarak I1 =  21.087095664475306
jarak I2 =  20.83130955811703
jarak I3 =  23.607698869111033
jarak I4 =  26.469986358769873


## INISIALISASI PARAMETER

In [59]:
# Inisialisasi Parameter
Pc = 0.95 #kemungkinan untuk melakukan crossover
Pm = 0.01 #kemungkinan untuk melakukan mutasi


"""
#hitung kualitas terbaik
def hitungKualitas(P, daftarKota):
    jarak = 0
    for i in range(jumlahKota):
        jarak += ((daftarKota[P[i][j]][0] - daftarKota[P[i-1][j]][0])**2 + (daftarKota[P[i][j]][1] - daftarKota[P[i-1][j]][1])**2)**0.5
    return jarak
"""

#Menghitung kualitas solusi (fitness)
def hitungKualitas(P, daftarKota):
    jarak = 0
    for i in range(jumlahKota):
        jarak += ((daftarKota[P[i][j]][0] - daftarKota[P[i-1][j]][0])**2 + (daftarKota[P[i][j]][1] - daftarKota[P[i-1][j]][1])**2)**0.5
        print(jarak[i])
    return jarak

IndexError: index 7 is out of bounds for axis 0 with size 5

In [39]:
print('a')

a
